bind = $mainMod SHIFT, j, hy3:movewindow, d        
bind = $mainMod SHIFT, k, hy3:movewindow, u        
bind = $mainMod SHIFT, l, hy3:movewindow, r
bind = $mainMod SHIFT, h, hy3:movewindow, l

bindm = $mainMod, mouse:273, resizewindow
