bind = $mainMod SHIFT, h, swapwindow, l
bind = $mainMod SHIFT, l, swapwindow, r
bind = $mainMod SHIFT, k, swapwindow, u
bind = $mainMod SHIFT, j, swapwindow, d

bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod CTRL, h, resizeactive, -$gap 0
bind = $mainMod CTRL, l, resizeactive, $gap 0
bind = $mainMod CTRL, k, resizeactive, 0 -$gap
bind = $mainMod CTRL, j, resizeactive, 0 $gap
