bind = $mainMod + SHIFT, h, swapwindow, l
bind = $mainMod + SHIFT, l, swapwindow, r
bind = $mainMod + SHIFT, k, swapwindow, u
bind = $mainMod + SHIFT, j, swapwindow, d

bindm = $mainMod, mouse:273, resizewindow
