bind = $mainMod, K, killactive,
bind = $mainMod, N, exec, $terminal
bind = $mainMod, I, exec, $wallpaper
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, P, exec, $menu
bind = $mainMod, X, exec, $setting
bind = $mainMod, C, exec, $lock
bind = $mainMod, E, exec, $bar
bind = $mainMod, A, layoutmsg, addmaster
bind = $mainMod, R, layoutmsg, removemaster
bind = $mainMod, Tab, exec, hyprctl dispatch hyprexpo:expo  
