bind = $mainMod, M, killactive,
bind = $mainMod, N, exec, $terminal
bind = $mainMod, I, exec, $wallpaper
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, R, exec, $menu
bind = $mainMod, X, exec, $setting
bind = $mainMod, C, exec, $lock
bind = $mainMod, B, exec, $bar


