bind = $mainMod, bracketright, workspace, +1
bind = $mainMod, bracketleft, workspace, -1
bind = $mainMod SHIFT, bracketright, movetoworkspace, +1
bind = $mainMod SHIFT, bracketleft, movetoworkspace, -1

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bindm = $mainMod, mouse:272, movewindow
