group {
  insert_after_current = true
  focus_removed_window = true
  merge_groups_on_drag = true
    groupbar {
    enabled = true
    font_family = Sans
    font_size = 10

    height = 22
    padding = 4
    spacing = 4

    text_color = rgba(ddddddff)

    col.active = rgba(33ccffcc)
    col.inactive = rgba(444444aa)
    col.locked_active = rgba(ffaa00cc)
    col.locked_inactive = rgba(555555aa)
  }
}
