dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = inherit
    allow_small_split = true
    new_on_active = after
    drop_at_cursor = on
    mfact = 0.52
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
