exec-once=fcitx5 -d -r
exec-once=fcitx5-remote -r

exec-once=noctalia-shell

exec-once=mkdir -p Documents Documents/Store Documents/Notes Pictures Pictures/Screenshots 
exec-once=mkdir -p Laboratory Playground Music Projects

exec-once=thunderbird syncthing
