# variables
source = $HOME/.config/hypr/variables.conf

# bingdings
source = $HOME/.config/hypr/bindings/bindings.conf

# effects
source = $HOME/.config/hypr/effects/effects.conf

# plugins
source = $HOME/.config/hypr/plugins/plugins.conf

# autostart
source = $HOME/.config/hypr/autostart.conf

# interaction
source = $HOME/.config/hypr/interaction.conf

