# Never change the order of the list

source = ./variables.conf

source = ./autostart.conf

source = ./effects/effects.conf

source = ./bindings/bindings.conf

source = ./plugins/plugins.conf

source = ./interaction.conf
