# bingdings
source = ~/.config/hypr/bindings.conf

# effects
source = ~/.config/hypr/effects/effects.conf

# plugins
source = ~/.config/hypr/plugins/plugins.conf

# autostart
source = ~/.config/hypr/autostart.conf

# interaction
source = ~/.config/hypr/interaction.conf

# variables
source = ~/.config/hypr/variables.conf

