input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0.0

    scroll_factor = 2.0

    touchpad {
        natural_scroll = true
    }

    special_fallthrough = true
    focus_on_close = 1
}

device {
    name = usb-optical-mouse-
    sensitivity = -0.5
    scroll_factor = 1.5
}

device {
    name = usb-optical-mouse--keyboard-1
    sensitivity = -0.5
    scroll_factor = 1.5
}

gestures {
}

monitor=,preferred,auto,auto
monitor=eDP-1,preferred,auto,1

