listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restor.
}

listener {
    timeout = 300 # 5 minutes = 300 seconds
    on-timeout = hyprlock
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
