source = hyprland/monitors.conf
source = hyprland/programs.conf
source = hyprland/autostart.conf
source = hyprland/env.conf
source = hyprland/effects.conf
source = hyprland/inputs.conf
source = hyprland/keys.conf
source = hyprland/rules.conf

