# -------------------------------
# Dim screen after 2.5 minutes
# -------------------------------
listener {
    timeout = 150                    # 2.5 minutes
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r     
}

# -------------------------------
# Lock screen after 5 minutes
# -------------------------------
listener {
    timeout = 300                    # 5 minutes
    on-timeout = sh -c 'brightnessctl -r; hyprlock'  
}

# -------------------------------
# Suspend after 15 minutes
# -------------------------------
listener {
    timeout = 900                    # 15 minutes
    on-timeout = sh -c 'brightnessctl -r; systemctl suspend'  
}

