$shell = bash
$fileManager = nautilus
$terminal = wezterm
$menu = noctalia-shell ipc call launcher toggle
$session = noctalia-shell ipc call sessionMenu toggle
$wallpaper = noctalia-shell ipc call wallpaper toggle
