$shell = bash
$fileManager = nautilus
$terminal = wezterm
$menu = noctalia-shell ipc call launcher toggle
$wallpaper = noctalia-shell ipc call wallpaper toggle
$atcoder = atcoder.jp
$codeberg = codeberg.org
$mazii = mazii.net
$session = librewolf --new-tab $codeberg --new-tab $mazii --new-tab $atcoder
